diff a/example/Makefile b/example/Makefile	(rejected hunks)
@@ -1,39 +1,26 @@
 CC=clang
-LD=clang -Wall -pedantic -std=gnu11 -fno-strict-aliasing
-CFLAGS=-g -O0
+LD=clang
+CFLAGS=-g -Os -Wall -pedantic
 LDFLAGS=
 
-TARGET=example.out
+TARGET=example
 
-SOURCES=\
-    test.c\
-    example_server.c\
-    example_client.c\
-    slac/slacassoc.c\
-    slac/powerlinegp_evse_slac.c\
+SOURCES=$(wildcard *.c slac/*.c)
+OBJECTS=$(SOURCES:.c=.o)
 
-HEADERS=\
+LIBS=\
+	-L..\
+	-lnikolav2g\
+	-lmultitask\
+	-lOpenV2G\
+	-lpolarssl\
+	-lm\
+	-lrt\
+	-lpthread\
 
-OBJECTS=\
-    $(SOURCES:.c=.o)\
+INCLUDES=-I..
 
-LIBS=\
-../libnikolav2g.a\
--lmultitask\
--lOpenV2G\
--lmbedtls\
--lm\
--lrt\
--lpthread\
-
-INCLUDES=\
-    -Islac/\
-    -I../\
-    -I../utils/libmultitask/unix\
-    -I../utils/OpenV2G_0.9.3/src/codec\
-    -I../utils/OpenV2G_0.9.3/src/appHandshake\
-    -I../utils/OpenV2G_0.9.3/src/transport\
-    -I../utils/OpenV2G_0.9.3/src/xmldsig\
+all: $(TARGET)
 
 .c.o:
 	$(CC) $(CFLAGS) $(INCLUDES) -c -o $@ $<
